settings:
  tpa_countdown: 0
  expired_time: 15 # seconds
  teleport:
    action_bar: true
    title: true

messages:
  player_not_found: "&cPlayer not found!"
  enter_player: "&cEnter the player name."

  usage_tpahere: "&cUse: /tpahere <player> to send a tpahere request."
  usage_tpa: "&cUse: /tpa <player> to send a tpa request."

  cant_tpa_yourself: "&cYou can't sent a request to yourself."

  no_requests: "&cYou have not received any requests from this player."

  request_sent: "&aYou sent the {type} request for {receiver}!"
  request_received: "&eYou received a {type} request from {sender}!"

  receiver_accept: "&aYou accepted {type}'s request!"
  sender_notify_accept: "&aThe {type}'s request was accepted."

  receiver_refuse: "&cYou refused {type}'s request!"
  sender_notify_refuse: "&cThe {type}'s request was refused."

  teleport:
    messages:
      cancelled: "&cTeleportation cancelled."
      success: "&aTeleportation completed."
      progress: "&eYou will be teleported in {time} seconds!"
    action_bar:
      progress: "&b{time} seconds"
      cancel: "&cTeleportation cancelled"
      success: "&aTeleportation completed"
    title:
      progress_title: "&3Teleportation in progress..."
      progress_sub_title: "&f{time}"
      cancelled_title: "&cTeleportation cancelled"
      cancelled_sub_title: "&fYou moved!"
      success_title: "&aTeleported successfully!"
      success_sub_title: "&fYou have been teleported!"

guis:
  sent_confirm:
    title: "Confirm Request"
    rows: 3

    info:
      slot: 13
      display_name: "&e{receiver}"
      lore:
        - ""
        - "&fPlayer to whom the teleportation request should be sent."
      glow: false

    accept:
      slot: 16
      type: LIME_STAINED_GLASS_PANE
      display_name: "&aConfirm"
      lore:
        - ""
        - "&fLeft click to confirm the request"
      glow: false

    refuse:
      slot: 10
      type: RED_STAINED_GLASS_PANE
      display_name: "&cCancel"
      lore:
        - ""
        - "&fLeft click to cancel the request"
      glow: false

  accept_request:
    title: "Response Request"
    rows: 3

    info:
      slot: 13
      display_name: "&e{receiver}"
      lore:
        - ""
        - "&fWill you accept teleportation from this player?"
      glow: false

    accept:
      slot: 16
      type: LIME_STAINED_GLASS_PANE
      display_name: "&aConfirm"
      lore:
        - ""
        - "&fLeft click to accept the teleport"
      glow: false

    refuse:
      slot: 10
      type: RED_STAINED_GLASS_PANE
      display_name: "&cCancel"
      lore:
        - ""
        - "&fLeft click to cancel the teleport"
      glow: false